'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowLeft, Check, CheckCircle2, ChevronRight, Clock3, FileText, LayoutDashboard, Plus, Search, ShieldCheck, Sparkles, X, AlertTriangle, BookOpen, History, RefreshCw, Receipt, Loader2, LogOut } from 'lucide-react';
import { CATEGORIES, POLICY, checks, effectiveCategory, totals, today, type Claim, type Workspace, type Category } from '@/lib/core';
const money = (amount: number, currency: string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 2 }).format(amount);
const stamp = (s: string) => new Date(s).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
const initials = (s: string) => s.split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase();
function Badge({ value }: {
    value: string;
}) { return <span className={`badge ${value.toLowerCase().replaceAll(' ', '-')}`}><span />{value}</span>; }
export default function Home() {
    const [workspace, setWorkspace] = useState<Workspace>({ claims: [] }), [revision, setRevision] = useState(0), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [ai, setAI] = useState(false), [actor, setActor] = useState('Reviewer');
    const [page, setPage] = useState('claims'), [selected, setSelected] = useState<string | null>(null), [query, setQuery] = useState(''), [filter, setFilter] = useState('All claims'), [showNew, setShowNew] = useState(false), [modal, setModal] = useState(''), [reason, setReason] = useState(''), [override, setOverride] = useState<Category>('Meals'), [amendText, setAmendText] = useState(''), [amendReceipt, setAmendReceipt] = useState(false), [tab, setTab] = useState('review');
    const claim = workspace.claims.find(c => c.id === selected);
    const closed = claim?.status === 'Approved' || claim?.status === 'Rejected';
    async function load() { setLoading(true); setError(''); try {
        const r = await fetch('/api/workspace');
        const d: any = await r.json();
        if (!r.ok)
            throw new Error(d.error);
        setWorkspace(d.workspace);
        setRevision(d.revision);
        setAI(d.aiConfigured);
        setActor(d.actor);
    }
    catch (e) {
        setError((e as Error).message);
    }
    finally {
        setLoading(false);
    } }
    useEffect(() => { load(); }, []);
    useEffect(() => { if (!notice)
        return; const id = setTimeout(() => setNotice(''), 6000); return () => clearTimeout(id); }, [notice]);
    useEffect(() => { function esc(e: KeyboardEvent) { if (e.key === 'Escape' && !busy) {
        setModal('');
        setShowNew(false);
    } } window.addEventListener('keydown', esc); return () => window.removeEventListener('keydown', esc); }, [busy]);
    async function mutate(action: string, extra: Record<string, unknown> = {}) {
        setBusy(action);
        setError('');
        try {
            const r = await fetch('/api/workspace', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, revision, id: selected, ...extra }) });
            const d: any = await r.json();
            if (!r.ok)
                throw new Error(d.error);
            setWorkspace(d.workspace);
            setRevision(d.revision);
            setModal('');
            setShowNew(false);
            setNotice(action === 'review' ? 'AI review saved. A human decision is still required.' : 'Changes saved successfully.');
            if (action === 'create')
                setSelected(d.workspace.claims[0].id);
            return true;
        }
        catch (e) {
            setError((e as Error).message);
            return false;
        }
        finally {
            setBusy('');
        }
    }
    function openDecision(action: string) { setReason(''); setModal(action); setOverride((claim && effectiveCategory(claim) !== 'Unclassified' ? effectiveCategory(claim) : 'Meals') as Category); setAmendText(claim?.description ?? ''); setAmendReceipt(claim?.receipt ?? false); }
    const counts = { pending: workspace.claims.filter(c => c.status === 'Pending').length, flagged: workspace.claims.filter(c => c.status !== 'Approved' && c.status !== 'Rejected' && checks(c, workspace.claims).some(f => f.level !== 'pass')).length, approved: workspace.claims.filter(c => c.status === 'Approved').length };
    const visible = workspace.claims.filter(c => (filter === 'All claims' || c.status === filter) && (c.claimant + ' ' + c.description + ' ' + c.id).toLowerCase().includes(query.toLowerCase()));
    const sum = totals(workspace.claims);
    const history = workspace.claims.flatMap(c => c.history.map(e => ({ ...e, claimId: c.id, claimant: c.claimant }))).sort((a, b) => b.at.localeCompare(a.at));
    return <div className="shell">
 <aside className="sidebar"><a href="/" className="brand"><span className="brand-icon"><ShieldCheck size={24}/></span>claimwise<span className="brand-dot">.</span></a><div className="workspace-label">REVIEW WORKSPACE</div><nav>{[{ id: 'claims', name: 'Expense claims', icon: LayoutDashboard }, { id: 'policy', name: 'Policy library', icon: BookOpen }, { id: 'activity', name: 'Activity log', icon: History }].map(n => <button key={n.id} className={page === n.id ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(n.id); setSelected(null); }}><n.icon size={19}/>{n.name}{n.id === 'claims' && <span className="nav-count">{workspace.claims.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="human-note"><ShieldCheck size={21}/><strong>AI assists. You decide.</strong><p>Every final decision stays with a human reviewer.</p></div><div className="profile"><span className="avatar small">{initials(actor)}</span><div><strong>Review workspace</strong><span title={actor}>{actor}</span></div><a href="/api/logout" title="Sign out"><LogOut size={16}/></a></div></div></aside>
 <div className="main-shell"><header className="topbar"><div>Workspace <ChevronRight size={14}/><strong>{page === 'policy' ? 'Policy library' : page === 'activity' ? 'Activity log' : 'Expense claims'}</strong></div><span className="private-label"><span />Reviewer workspace</span></header><main>
 {error && <div className="alert error" role="alert"><AlertTriangle size={19}/><span>{error}</span><button onClick={load} disabled={!!busy}>Reload</button></div>}
 {notice && <div className="toast" role="status"><CheckCircle2 size={18}/>{notice}</div>}
 {!ai && !loading && <div className="config-banner"><Sparkles size={17}/><span><strong>Live AI setup pending.</strong> Policy checks and claim management are ready. An API connection is needed to run AI reviews.</span></div>}
 {page === 'claims' && !claim && <>
 <div className="heading"><div><div className="eyebrow">EXPENSE OPERATIONS</div><h1>A clearer view of every claim.</h1><p>Review expenses with policy evidence. Make decisions with confidence.</p></div><button className="primary" onClick={() => { setError(''); setShowNew(true); }} disabled={loading || !!busy}><Plus size={18}/>New claim</button></div>
 <div className="stats"><div className="stat"><span>Total submitted<FileText size={18}/></span><strong>{Object.keys(sum).length ? Object.entries(sum).map(([currency, cents]) => <span className="currency-total" key={currency}>{money(cents / 100, currency)}</span>) : '₹0'}</strong><small>{workspace.claims.length} claims · totals kept by currency</small></div><div className="stat"><span>Awaiting decision<Clock3 size={18}/></span><strong>{counts.pending}</strong><small>Ready for your attention</small></div><div className="stat"><span>Policy flags<AlertTriangle size={18}/></span><strong className="amber-text">{counts.flagged}</strong><small>Open claims needing a closer look</small></div><div className="stat"><span>Approved<CheckCircle2 size={18}/></span><strong className="green-text">{counts.approved}</strong><small>Reviewed and approved by you</small></div></div>
 <section className="claims-panel"><div className="panel-heading"><div><h2>Claims inbox <span className="count">{workspace.claims.length}</span></h2><p>All the details. One place to review.</p></div><button className="icon-button" aria-label="Refresh claims" onClick={load} disabled={loading || !!busy}><RefreshCw size={17} className={loading ? 'spin' : ''}/></button></div><div className="toolbar"><div className="tabs">{['All claims', 'Pending', 'Clarification requested', 'Approved', 'Rejected'].map(s => <button className={filter === s ? 'active' : ''} key={s} onClick={() => setFilter(s)}>{s === 'Clarification requested' ? 'Clarification' : s}</button>)}</div><label className="search"><Search size={17}/><input placeholder="Search claims…" value={query} onChange={e => setQuery(e.target.value)} aria-label="Search claims"/></label></div>
 {loading ? <div className="empty"><Loader2 className="spin"/><h3>Loading your workspace</h3><p>Getting the latest claims and review history.</p></div> : !workspace.claims.length ? <div className="empty"><div className="empty-icon"><Receipt size={30}/></div><h3>Your claims inbox starts here</h3><p>Add your first expense or explore six sample claims<br />with duplicates, missing receipts, and policy exceptions.</p><div className="button-row"><button className="primary" onClick={() => setShowNew(true)}><Plus size={16}/>Create a claim</button><button className="secondary" disabled={!!busy} onClick={() => mutate('seed')}>{busy === 'seed' ? 'Adding samples…' : 'Explore sample claims'}<ArrowUpRight size={16}/></button></div></div> : visible.length === 0 ? <div className="empty"><Search /><h3>No matching claims</h3><p>Try a different search or status.</p><button className="secondary" onClick={() => { setQuery(''); setFilter('All claims'); }}>Clear filters</button></div> : <div className="table-scroll"><table><thead><tr><th>Claimant / expense</th><th>Category</th><th>Amount</th><th>Status</th><th>Policy check</th><th /></tr></thead><tbody>{visible.map((c, i) => { const flags = checks(c, workspace.claims).filter(f => f.level !== 'pass'); return <tr key={c.id} onClick={() => { setSelected(c.id); setTab('review'); }}><td><div className="person-cell"><span className={`avatar color-${i % 4}`}>{initials(c.claimant)}</span><div><button className="claim-link" onClick={() => { setSelected(c.id); setTab('review'); }}>{c.claimant}</button><span>{c.description}</span></div></div></td><td><span className="category">{effectiveCategory(c)}</span><small className="cell-sub">{c.date}</small></td><td className="amount">{money(c.amount, c.currency)}</td><td><Badge value={c.status}/></td><td>{flags.length ? <span className="flag"><AlertTriangle size={14}/>{flags.length} {flags.length === 1 ? 'flag' : 'flags'}</span> : <span className="clear"><CheckCircle2 size={14}/>Checks passed</span>}</td><td><ChevronRight size={16}/></td></tr>; })}</tbody></table></div>}
 <div className="table-footer"><span>{visible.length} of {workspace.claims.length} claims</span><span><ShieldCheck size={14}/>Backed by sample policy v1.0</span></div></section><div className="bottom-note"><BookOpen size={16}/><p><strong>A transparent starting point.</strong> This demo uses a sample policy, not an organizational policy. Review its rules before making decisions.</p><button onClick={() => setPage('policy')}>View policy <ArrowUpRight size={15}/></button></div></>}
 {page === 'claims' && claim && <>
 <button className="back" onClick={() => setSelected(null)}><ArrowLeft size={16}/>Back to claims</button><div className="heading detail-heading"><div><div className="eyebrow">{claim.id}</div><h1>{claim.claimant}’s claim</h1><p>Submitted {stamp(claim.createdAt)} <span className="dot-sep">·</span> <Badge value={claim.status}/></p></div><strong className="claim-amount">{money(claim.amount, claim.currency)}</strong></div>
 <div className="detail-grid"><div><section className="card"><div className="section-title"><h2>Expense details</h2><Receipt size={19}/></div><div className="detail-fields"><div><label>Expense date</label><strong>{claim.date}</strong></div><div><label>Declared category</label><strong>{claim.category}</strong></div><div><label>Receipt</label><strong className={claim.receipt ? 'green-text' : 'amber-text'}>{claim.receipt ? 'Available' : 'Missing'}</strong></div><div><label>Currency</label><strong>{claim.currency}</strong></div></div><div className="description"><label>Business purpose / description</label><p>{claim.description}</p></div>{!closed && <button className="text-button" onClick={() => openDecision('amend')}>Add clarification or receipt information <ArrowUpRight size={14}/></button>}</section>
 <section className="card"><div className="section-title"><h2>Policy checks</h2><span className="tiny-label">DETERMINISTIC</span></div><div className="check-list">{checks(claim, workspace.claims).map((f, i) => <div key={i} className={`check-row ${f.level}`}>{f.level === 'pass' ? <CheckCircle2 size={18}/> : <AlertTriangle size={18}/>}<div><p>{f.message}</p><button className="citation" onClick={() => setPage('policy')}>{f.sectionId} · {POLICY.sections.find(s => s.id === f.sectionId)?.title}</button></div></div>)}</div><p className="micro">Checks flag issues for review; passing them does not establish business eligibility.</p></section>
 <section className="card"><div className="tabs detail-tabs"><button className={tab === 'review' ? 'active' : ''} onClick={() => setTab('review')}>AI review</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>History <span className="count">{claim.history.length}</span></button></div>{tab === 'history' ? <div className="history-list">{[...claim.history].reverse().map(e => <div className="history-item" key={e.id}><span className="history-dot"/><div><strong>{e.type}</strong><small>{stamp(e.at)} · {e.actor}</small><p>{e.reason}</p>{e.details !== undefined && <details><summary>View recorded details</summary><pre>{JSON.stringify(e.details, null, 2)}</pre></details>}</div></div>)}</div> : claim.review ? <><div className="ai-result-heading"><Sparkles size={20}/><strong>{claim.review.assessment === 'may_comply' ? 'May comply with policy' : claim.review.assessment === 'clarification' ? 'Clarification recommended' : 'Needs human review'}</strong></div><div className="review-meta"><span>Category: {claim.review.category}</span><span className={claim.review.uncertain ? 'uncertain' : 'confident'}>{claim.review.uncertain ? 'Uncertain classification' : 'Classification not flagged uncertain'}</span></div><p className="review-summary">{claim.review.summary}</p>{claim.review.findings.map((f, i) => <div className="ai-finding" key={i}><p>{f.message}</p>{f.sectionIds.map(id => { const s = POLICY.sections.find(s => s.id === id); return <details className="evidence" key={id}><summary><BookOpen size={13}/>{id} · {s?.title}</summary><p>{s?.text}</p></details>; })}</div>)}{claim.review.questions.length > 0 && <div className="questions"><h3>Questions for the claimant</h3><ul>{claim.review.questions.map((q, i) => <li key={i}>{q}</li>)}</ul></div>}<p className="micro">{claim.review.model} · {stamp(claim.review.at)} · {claim.review.policyVersion}</p></> : <div className="ai-empty"><span className="ai-orb"><Sparkles size={24}/></span><h3>A second look, grounded in policy.</h3><p>Run an AI review to classify this expense, find relevant policy evidence, and surface missing information.</p></div>}</section></div>
 <aside className="review-aside"><section className="card decision-card"><div className="section-title"><h2>Review workspace</h2><ShieldCheck size={20}/></div><p>AI offers guidance. Your decision is the final step.</p><button className="primary full" disabled={!!busy || !ai || closed} onClick={() => mutate('review')}>{busy === 'review' ? <Loader2 size={17} className="spin"/> : <Sparkles size={17}/>} {busy === 'review' ? 'Reviewing policy…' : claim.review ? 'Run AI review again' : 'Run AI review'}</button>{!ai && <p className="micro">Live AI connection required.</p>}<div className="divider"/><h3>Your decision</h3>{closed ? <><p>This claim is closed. Its history is preserved.</p><button className="secondary full" onClick={() => openDecision('reopen')} disabled={!!busy}>Reopen claim</button></> : <><button className="approve full" onClick={() => openDecision('approve')} disabled={!!busy || !claim.review}><Check size={17}/>Approve claim</button>{!claim.review && <p className="micro">Run AI review before approving.</p>}<button className="secondary full" disabled={!!busy} onClick={() => openDecision('clarify')}>Request clarification</button><button className="reject full" disabled={!!busy} onClick={() => openDecision('reject')}>Reject claim</button><div className="divider"/><button className="text-button" disabled={!!busy} onClick={() => openDecision('override')}>Override classification <ArrowUpRight size={14}/></button></>}<div className="audit-note"><History size={15}/><span>Decisions and reasons are recorded in the claim history.</span></div></section><div className="policy-mini"><BookOpen size={20}/><h3>Sample policy v1.0</h3><p>INR limits · per claim<br />Receipts required for all expenses</p><button className="text-button" onClick={() => setPage('policy')}>Read the policy <ChevronRight size={14}/></button></div></aside></div></>}
 {page === 'policy' && <><div className="heading"><div><div className="eyebrow">POLICY LIBRARY</div><h1>The evidence behind every review.</h1><p>A small, explicit policy with traceable sections and deterministic limits.</p></div><span className="badge pending">Sample v1.0</span></div><div className="policy-notice"><BookOpen size={22}/><div><strong>Demonstration policy — not an employer policy</strong><p>No organizational policy was supplied. These illustrative rules are maintained in the versioned policy configuration. INR limits apply per claim, not per day or night.</p></div></div><div className="policy-grid">{POLICY.sections.map(s => <section className="card policy-section" key={s.id}><div className="section-title"><span className="section-number">{s.id}</span>{s.limit && <span className="limit">{money(s.limit, 'INR')} / claim</span>}</div><h2>{s.title}</h2><p>{s.text}</p></section>)}</div></>}
 {page === 'activity' && <><div className="heading"><div><div className="eyebrow">AUDIT TRAIL</div><h1>Every action has a history.</h1><p>Claim submissions, AI reviews, and human decisions in one timeline.</p></div><span className="count">{history.length} events</span></div><section className="card">{!history.length ? <div className="empty"><History size={30}/><h3>No activity yet</h3><p>Actions will appear here when you start reviewing claims.</p></div> : <div className="history-list">{history.map(e => <div className="history-item" key={e.id}><span className="history-dot"/><div><strong>{e.type} <button className="text-button inline" onClick={() => { setSelected(e.claimId); setPage('claims'); setTab('history'); }}>{e.claimant} <ArrowUpRight size={13}/></button></strong><small>{stamp(e.at)} · {e.actor} · {e.claimId}</small><p>{e.reason}</p>{e.details !== undefined && <details><summary>Recorded details</summary><pre>{JSON.stringify(e.details, null, 2)}</pre></details>}</div></div>)}</div>}</section></>}
 <footer>Claimwise <span>Policy evidence. Human judgment.</span><span>Sample workspace · No payments are processed</span></footer>
 </main></div>
 {showNew && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="new-title"><div className="section-title"><div><div className="eyebrow">NEW EXPENSE</div><h2 id="new-title">Create a claim</h2></div><button className="icon-button" aria-label="Close" disabled={!!busy} onClick={() => setShowNew(false)}><X size={20}/></button></div><p className="muted">Add the expense details. Policy checks run automatically.</p><form onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); await mutate('create', { claim: { claimant: f.get('claimant'), date: f.get('date'), category: f.get('category'), amount: Number(f.get('amount')), currency: f.get('currency'), description: f.get('description'), receipt: f.get('receipt') === 'yes' } }); }}><label>Claimant<input autoFocus required name="claimant" maxLength={120} placeholder="Employee’s full name"/></label><div className="form-grid"><label>Expense date<input required type="date" name="date" min="2000-01-01" max={today()} defaultValue={today()}/></label><label>Category<select name="category" defaultValue="Unclassified"><option>Unclassified</option>{CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label><label>Amount<input required name="amount" type="number" step="0.01" min="0.01" max="10000000" placeholder="0.00"/></label><label>Currency<select name="currency">{['INR', 'USD', 'EUR', 'GBP'].map(c => <option key={c}>{c}</option>)}</select></label></div><label>Description & business purpose<textarea name="description" required minLength={5} maxLength={2000} rows={3} placeholder="What was purchased, and why? Include attendees, travel route, or stay dates where relevant."/></label><label>Receipt available?<select name="receipt"><option value="yes">Yes — receipt available</option><option value="no">No — receipt missing</option></select></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={!!busy} onClick={() => setShowNew(false)}>Cancel</button><button className="primary" disabled={!!busy}>{busy === 'create' ? <Loader2 className="spin" size={16}/> : <Plus size={16}/>}Create claim</button></div></form></section></div>}
 {modal && claim && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="decision-title"><div className="section-title"><h2 id="decision-title">{{ approve: 'Approve claim', reject: 'Reject claim', clarify: 'Request clarification', override: 'Override classification', amend: 'Add claim information', reopen: 'Reopen claim' }[modal]}</h2><button className="icon-button" disabled={!!busy} onClick={() => setModal('')} aria-label="Close"><X size={20}/></button></div><p className="muted">{claim.claimant} · {money(claim.amount, claim.currency)} · {claim.id}</p>{modal === 'approve' && <div className="approval-warning">Confirm that you reviewed the policy evidence and any open flags. Approval records your decision; it does not issue a payment.</div>}<form onSubmit={e => { e.preventDefault(); mutate(modal, { reason, category: override, description: amendText, receipt: amendReceipt }); }}>{modal === 'override' && <label>Correct category<select value={override} onChange={e => setOverride(e.target.value as Category)}>{CATEGORIES.map(c => <option key={c}>{c}</option>)}</select><small>A new AI review will be required. The previous review is preserved.</small></label>}{modal === 'amend' && <><label>Updated description<textarea required minLength={5} maxLength={2000} rows={4} value={amendText} onChange={e => setAmendText(e.target.value)}/></label><label>Receipt available?<select value={String(amendReceipt)} onChange={e => setAmendReceipt(e.target.value === 'true')}><option value="true">Yes</option><option value="false">No</option></select></label></>}<label>{modal === 'clarify' ? 'Question for the claimant' : 'Reason for this action'}<textarea autoFocus required maxLength={2000} rows={3} value={reason} onChange={e => setReason(e.target.value)} placeholder="Explain your decision so another reviewer can follow it."/></label>{modal === 'clarify' && <p className="micro">This request is recorded in the app. No email is sent.</p>}{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={!!busy} onClick={() => setModal('')}>Cancel</button><button className="primary" disabled={!!busy || !reason.trim()}>{busy ? <Loader2 size={16} className="spin"/> : <Check size={16}/>}Confirm {modal === 'approve' ? 'approval' : 'action'}</button></div></form></section></div>}
 </div>;
}
